version: '3'
services:
   express:
      build:
        context: contact-list
      container_name: "express-test"
      ports:
        - "3000:3000"
      links:
        - database
      depends_on:
        - database
   database:
      image: mongo
      container_name: "database"
      ports:
        - "27017:27017"
networks:
   front-end:
   back-end:
